name: Update iCal
on:
  schedule:
    - cron: "1 0 * * *"

jobs:
  build:
    name: Update
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: master
      - uses: actions/setup-node@v1
        with:
          node-version: "10.x"
      - run: npm install
      - name: Generate iCal files
        env:
          ACCESSTOKEN: ${{ secrets.ACCESSTOKEN }}
        run: npm run scripts:ical
      - name: Generate Timestamp
        run: |
          echo "Last updated on $(date +'%Y-%m-%d')" > output/INFO.md
      - name: Commit files
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add output/*
          git commit -m "Update ical files" -a
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
